- name: Set up node's network adapter
  copy:
      src: files/rover.network
      dest: /etc/systemd/network/rover.network

- name: Disable NetworkManager for the interface
  copy:
      src: files/disable-eth0.conf
      dest: /etc/NetworkManager/conf.d/disable-eth0.conf

- name: Restart NetworkManager
  systemd: name=NetworkManager.service state=restarted

- name: Enable systemd-networkd
  systemd:
      name: systemd-networkd.service
      state: started
      enabled: yes

<<<<<<< HEAD
=======
- name: Copy service file
  copy:
      src: files/can.service
      dest: /etc/systemd/system/can.service

>>>>>>> [teleop, nav, percep, loc, sim] auton integration (#962)
- name: Reload systemd
  systemd: 
      daemon_reload: yes
